// Code generated by mockery v2.37.1. DO NOT EDIT.

package transport

import (
	domain "go-ticketos/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTicketCategoryAdapter is an autogenerated mock type for the TicketCategoryAdapter type
type MockTicketCategoryAdapter struct {
	mock.Mock
}

// ToResponseDTO provides a mock function with given fields: tc
func (_m *MockTicketCategoryAdapter) ToResponseDTO(tc domain.TicketCategory) TicketCategoryResponseDTO {
	ret := _m.Called(tc)

	var r0 TicketCategoryResponseDTO
	if rf, ok := ret.Get(0).(func(domain.TicketCategory) TicketCategoryResponseDTO); ok {
		r0 = rf(tc)
	} else {
		r0 = ret.Get(0).(TicketCategoryResponseDTO)
	}

	return r0
}

// NewMockTicketCategoryAdapter creates a new instance of MockTicketCategoryAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketCategoryAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketCategoryAdapter {
	mock := &MockTicketCategoryAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
