// Code generated by mockery v2.37.1. DO NOT EDIT.

package domain

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockPromocodeRepo is an autogenerated mock type for the PromocodeRepo type
type MockPromocodeRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: promocode
func (_m *MockPromocodeRepo) Create(promocode Promocode) error {
	ret := _m.Called(promocode)

	var r0 error
	if rf, ok := ret.Get(0).(func(Promocode) error); ok {
		r0 = rf(promocode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *MockPromocodeRepo) GetByID(id uuid.UUID) (*Promocode, error) {
	ret := _m.Called(id)

	var r0 *Promocode
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*Promocode, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *Promocode); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Promocode)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPromocodeRepo creates a new instance of MockPromocodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromocodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromocodeRepo {
	mock := &MockPromocodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
