// Code generated by mockery v2.37.1. DO NOT EDIT.

package domain

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *MockOrderRepo) Create(order Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *MockOrderRepo) GetByID(id uuid.UUID) (*Order, error) {
	ret := _m.Called(id)

	var r0 *Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: order
func (_m *MockOrderRepo) Update(order Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
